upgrade to mapstruct</artifactId>                <version>1.5.0.Beta1</version> and downgrade project structure project module sdk to jdk 8 to run xsd normally to fix java.lang.NoClassDefFoundError: javax/xml/bind/JAXBElement error