upgrade to mapstruct</artifactId>                <version>1.5.0.Beta1</version> to run swagger-ep-assgn-review normally to fix java.lang.NoClassDefFoundError: javax/xml/bind/JAXBElement error